### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by tuck3rb** [tuck3rb/PictoApp#3]

**Comment by qsebring3930** [comment]
-Create A Navigator that can handle 4 screens

1. Home Screen
2. Sign in Page
3. Private Room Generate/Login
4. Chat Room

**Comment by tuck3rb** [comment]
Jayden got the navigator to connect the home and chat page!

**Comment by qsebring3930** [comment]
Changed Navigator to GoRouter like the tutorial in order to add sign in page

**Comment by tuck3rb** [comment]
Removed sign in features to allow anonymous chatting, for the true Picto[REDACTED] experience
